### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by Chik3r** [NarodGaming/hardwaremod-revamped#3]
Are you still working on this?

**Comment by Chik3r** [comment]
Also i wantto traslate to spanish but it says:
![image](https://user-images.githubusercontent.com/31808958/36005967-16de677a-0d19-11e8-81bb-b5caf8bf0e5c.png)

**Comment by NarodGaming** [comment]
As of right now, I am developing my game actively whilst just supporting the GitHub of this mod.

Regrettably, CrowdIn (the translation provider in your picture) is a paid for service and I obviously make no money from the mod. In order to translate the mod, it is now far more difficult. I will outline the steps and if you wish to continue you may:

1) Fork the mod
2) In this forked mod, either download a zip of it or download it through a program like SourceTree.
3) In the "hwmod" folder, go into "Software Types"
4) Every "Description" or "Name" tag has English next to it -> that needs translating
5) Do the same in the "Company Types" folder too.
6) (DO NOT RENAME ANY FILES)
7) Create a Pull Request and I will merge your work into the main mod, and then I will contact you and post the mod on the Steam Workshop with your full consent and your name as a developer.

**Comment by Chik3r** [comment]
OK

**Comment by Chik3r** [comment]
Also SoftwareType: A03. Mobile phone is missing </SoftwareType> at the end

**Comment by Chik3r** [comment]
And </Features>

**Comment by NarodGaming** [comment]
Yeah good spot, I don't believe that was a problem in the release of the mod on the workshop but those tags will be needed, I'll update the mod fixing this once I get the chance.
